import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" updated="25 August 2026">
      <LegalSection title="Who these terms are with">
        <p>ProveMyCV (provemycv.com) ("the Service") is currently operated by Eric Ndungu, trading as an individual/sole trader based in England. In these terms, "we", "us", and "our" refer to Eric Ndungu. If this changes to a registered company in future, these terms will be updated to reflect that. By using the Service, you agree to these terms. If you don't agree, please don't use the Service.</p>
      </LegalSection>

      <LegalSection title="What the Service does">
        <p>The Service lets you paste or upload a CV and other professional evidence, compare it against a job description or your current role, and see an automatically generated breakdown of what's directly evidenced, partially evidenced, or not found.</p>
        <p><strong className="text-foreground">This is decision support only.</strong> It does not determine employment eligibility, banding or grading decisions, legal rights, job-evaluation outcomes, or professional competence, for any profession. The output is generated by an AI model and can be incomplete, wrong, or miss context a human reviewer would catch. You're responsible for how you use the output — treat it as a starting point for your own review, not a verified or authoritative assessment.</p>
      </LegalSection>

      <LegalSection title="Who can use it">
        <p>You must be at least 18 years old to create an account. If you provide an email address, it must be one you actually control, and you're responsible for keeping your password secure and for anything that happens under your account.</p>
      </LegalSection>

      <LegalSection title="Your content">
        <p>You keep ownership of anything you submit — your CV, evidence documents, job descriptions, and any other text or files. By submitting content, you grant us a limited licence to process it solely to provide the Service to you (running the analysis, storing it in your account, sending it to the third-party processors described in our Privacy Policy). We don't use your content for any other purpose.</p>
        <p>You confirm you have the right to submit whatever you upload — don't submit anything that isn't yours to share, or anything unlawful, and don't attempt to use the Service to process someone else's personal data without their knowledge.</p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>Please don't: attempt to bypass rate limits or usage restrictions; use automated tools to scrape or bulk-submit content; attempt to access another user's account or data; reverse-engineer or attempt to extract the underlying prompts or models behind the analysis; or use the Service for any unlawful purpose. We may suspend or terminate access for any account that does.</p>
      </LegalSection>

      <LegalSection title="No warranty">
        <p>The Service is provided "as is". We don't guarantee it will be uninterrupted, error-free, or that the AI-generated analysis will be accurate or complete. To the fullest extent the law allows, we exclude all warranties, express or implied, about the Service's fitness for any particular purpose.</p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>To the fullest extent permitted by law, we won't be liable for any indirect, incidental, or consequential loss arising from your use of the Service, including any decision made on the basis of its output. Nothing in these terms excludes or limits liability that cannot lawfully be excluded or limited, including for death or personal injury caused by our negligence, or for fraud.</p>
      </LegalSection>

      <LegalSection title="Ending your use of the Service">
        <p>You can delete your account at any time from the "About you" screen — this permanently removes your account and everything in it. We may suspend or terminate an account that breaches the acceptable-use terms above, with notice where reasonably practicable.</p>
      </LegalSection>

      <LegalSection title="Changes">
        <p>We may update these terms or the Service itself as it develops. If we make a material change to these terms, we'll update the "Last updated" date above; continuing to use the Service after that means you accept the change.</p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>These terms are governed by the law of England and Wales, and any dispute will be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>Questions about these terms: <a href="mailto:privacy@provemycv.com" className="font-medium text-primary underline underline-offset-4">privacy@provemycv.com</a>.</p>
      </LegalSection>
    </LegalLayout>
  );
}
